version: '3.6'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
      # only build dev stage
      target: development
      # target: production

    # To run in DEBUG mode:  npm run start:debug
    command: npm run start:dev
    environment:
      DATABASE_URL: 
      NODE_ENV: development
      PORT: 3001
    ports:
      - 3001:3001
      - 9229:9229

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
      target: development
    command: npm run start
    ports:
      - "4200:4200"
    links: 
      - api
  database:
    image: postgres:14.3-alpine
    environment:
      - POSTGRES_USER=zion
      - POSTGRES_PASSWORD=zion
      - POSTGRES_DB=zion
    container_name: 'zion-postgres'
  zion:
    build: ./zion
    # image: vaimee/zion:latest
    depends_on:
      - database
    entrypoint: ['sh', '-c','npm run db:migrate:latest && npm run start:prod']
    ports: 
      - 3000:3000
    environment:
      - ZION_NODE_ENV=production
      - ZION_SERVER_PORT=3000
      # Using task name as explained in https://github.com/vaimee/zion/issues/11#issuecomment-1434457337
      - ZION_DB_HOST=database
      - ZION_DB_PORT=5432
      - ZION_DB_USER=zion
      - ZION_DB_PASSWORD=zion
      - ZION_DB_DATABASE=zion
      - ZION_JWT_SECRET=abc123
      - ZION_JWT_EXPIRES_IN=7d
    container_name: zion

